---
kind: pipeline
type: kubernetes
name: cicd

__orb: &rust
  image: registry-np.storage-system.svc.k8s.local:5000/orbs/rust:blue
  pull: always
  environment:
    SCCACHE_CREDS:
      from_secret: sccache-creds

steps:
  - name: just-check
    <<: *rust
    commands:
      - /with-ci.sh just check
  - name: just-udeps
    <<: *rust
    commands:
      - /with-ci.sh just udeps

trigger:
  branch:
    exclude:
      - renovate/*
