---
kind: pipeline
type: kubernetes
name: cicd

__dind_orb: &dind
  image: registry-np.storage-system.svc.k8s.local:5000/orbs/dind:blue
  pull: always
  volumes:
    - name: dockersock
      path: /var/run

__rust_orb: &rust
  image: registry-np.storage-system.svc.k8s.local:5000/orbs/rust:blue
  pull: always
  volumes:
    - name: dockersock
      path: /var/run
  environment:
    SCCACHE_CREDS:
      from_secret: sccache-creds

steps:
  - name: just-check
    <<: *rust
    commands:
      - /with-ci.sh just check
  - name: just-test
    <<: *rust
    commands:
      - /with-ci.sh just test
  - name: just-udeps
    <<: *rust
    commands:
      - /with-ci.sh just udeps
  - name: docker-daemon
    when:
      branch:
        - main
    <<: *dind
    privileged: true
    detach: true
  - name: just-dockerize
    when:
      branch:
        - main
    <<: *rust
    commands:
      - while ! curl -s --unix-socket /var/run/docker.sock http://localhost/; do sleep 1; done
      - just pull || (/with-ci.sh just release && just docker && just push)
      - just push-latest

trigger:
  branch:
    exclude:
      - renovate/*

volumes:
  - name: dockersock
    temp: {}
