---
kind: pipeline
type: kubernetes
name: cicd

__orb: &rust
  image: registry-np.storage-system.svc.k8s.local:5000/orbs/rust:blue
  pull: always
  environment:
    SCCACHE_BUCKET: sccache
    SCCACHE_ENDPOINT: minio.storage-system.svc.k8s.local
    SCCACHE_REGION: us-west-1
    SCCACHE_S3_USE_SSL: "off"
    SCCACHE_CREDS:
      from_secret: sccache-creds

steps:
  - name: just-check
    <<: *rust
    commands:
      - /with-sccache.sh just check
  - name: just-udeps
    <<: *rust
    commands:
      - /with-sccache.sh just udeps
