[changelog]
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## Unreleased
{% endif %}\
{% if previous %}\
    {% if previous.version and version %}
    ### Diff

    [{{ previous.version }}...{{ version }}](compare/{{ previous.version }}...{{ version }})
    {% endif %}\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | trim }} [#{{ commit.id | truncate(length=7, end="") }}](commit/{{ commit.id }})\
    {% endfor %}
{% endfor %}\n
"""

[git]
filter_unconventional = false
conventional_commits = false
commit_parsers = [
    { message = "^chore: Release", skip = true},
    { message = "^", group = "Changelog"},
]
