[target.x86_64-unknown-linux-musl]
image = "ghcr.io/rarescosma/orbs/cross-x86_64-unknown-linux-musl:blue"

[target.i686-unknown-linux-musl]
image = "ghcr.io/rarescosma/orbs/cross-i686-unknown-linux-musl:blue"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/rarescosma/orbs/cross-aarch64-unknown-linux-musl:blue"

[target.armv7-unknown-linux-musleabi]
image = "ghcr.io/rarescosma/orbs/cross-armv7-unknown-linux-musleabi:blue"

[target.powerpc64-unknown-linux-gnu]
image = "ghcr.io/rarescosma/orbs/cross-powerpc64-unknown-linux-gnu:blue"

[target.s390x-unknown-linux-gnu]
image = "ghcr.io/rarescosma/orbs/cross-s390x-unknown-linux-gnu:blue"
