name: test

on:
  push:
    branches:
      - "dev/test-yml"

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Run the CI tests
        run: just ci
